/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grank_pvalue_PValueNative */

#ifndef _Included_grank_pvalue_PValueNative
#define _Included_grank_pvalue_PValueNative
#ifdef __cplusplus
extern "C" {
#endif
#undef grank_pvalue_PValueNative_MAXN
#define grank_pvalue_PValueNative_MAXN 10000L
/*
 * Class:     grank_pvalue_PValueNative
 * Method:    lowerProb
 * Signature: ([D[II)D
 */
JNIEXPORT jdouble JNICALL Java_grank_pvalue_PValueNative_lowerProb
  (JNIEnv *, jclass, jdoubleArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
