/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_tkk_ics_jbliss_Graph_Vertex */

#ifndef _Included_fi_tkk_ics_jbliss_Graph_Vertex
#define _Included_fi_tkk_ics_jbliss_Graph_Vertex
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
